Project Management Application - MVC/Models/ErrorViewModel.cs
namespace Project_Management_Application___MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project Management Application - MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MySolution.Model;
using Services.FilesManager;
namespace Project_Management_Application_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private List<Project>? _projects = null;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            _projects = await FilesManager.GetProjects();
            return View(_projects);
        }
    }
}

Project Management Application - MVC/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using MySolution.Model;
using Services.FilesManager;
namespace Project_Management_Application_MVC.Controllers
{
    public class ProjectsController : Controller
    {
        private List<Project>? _projects = null;
        public ProjectsController()
        {
            ReadProjects(); 
        }
        public async void ReadProjects()
        {
            _projects = await FilesManager.GetProjects();
        }
        public IActionResult ProjectDetails(string projectName)
        {
            var pro = _projects.Select(p => p).Where(p => p.ProjectName == projectName).ToList()[0];
            return View(pro);
        }
    }
}

Project Management Application - MVC/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using MySolution.Model;
using Services.FilesManager;
using Services.Filtration;

namespace Project_Management_Application_MVC.Controllers
{
    public class SearchController : Controller
    {
        private List<Project>? _projects = null;
        public SearchController()
        {
            ReadProjects();
        }
        public async void ReadProjects()
        {
            _projects = await FilesManager.GetProjects();
        }
        public IActionResult Index()
        {
            List<MySolution.Model.MyTask> tasks= new();
            return View(tasks);
        }
        [HttpPost]
        public ActionResult Index(string ProjectName, string TaskName, StatusType TaskStatus, string AssignedContributor)
        {
            TaskFilter taskfilter = new TaskFilter();
            if (TaskStatus != null)
                taskfilter.TaskStatus = TaskStatus;
            if (TaskName != null)
                taskfilter.TaskName = TaskName;
            if (ProjectName != null)
                taskfilter.ProjectName = ProjectName;
            if (AssignedContributor != null)
                taskfilter.AssignedContributor = AssignedContributor;
            List<MySolution.Model.MyTask> tasks = TasksFiltration.Search(_projects, taskfilter);
            return View(tasks);
        }
    }
}

Project Management Application - MVC/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using MySolution.Model;
using Services.FilesManager;

namespace Project_Management_Application_MVC.Controllers
{
    public class UsersController : Controller
    {
        private List<Project>? _projects = null;
        public UsersController()
        {
            ReadProjects();
        }
        public async void ReadProjects()
        {
            _projects = await FilesManager.GetProjects();
        }
        public async Task<IActionResult> UserDetails(string userName)
        {
            ViewBag.UserName = userName;
            var query = _projects.Select(p => p).Where(p => p.Contributors.Contains(userName)).ToList();
            return View(query);
        }
    }
}

Project Management Application - MVC/Views/Home/Index.cshtml
@model IEnumerable<MySolution.Model.Project>

@{
    ViewData["Title"] = "Home Page";
}

<div class="indexContent">
    <h1 class="title">Your Projects</h1>
    <div style="padding:50px">
    <table class = "Table">
        <tr style="font-weight:600">
            <td class="line"> Project Name </td>
            <td class="line"> Number Of Tasks </td>
            <td class="line"> Number Of Assigned Collaborators </td>
        </tr>

        @{
            foreach(var project in Model)
            {
                <tr> 
                    <td><a class="link" href='@Url.Action("ProjectDetails", "Projects", new {projectName = @project.ProjectName})'>@project.ProjectName</a></td>
                    <td>@project.Tasks.Count</td>
                    <td>@project.Contributors.Count</td>
                </tr>
            }
        }
    </table>
    </div>
</div>

Project Management Application - MVC/Views/Projects/ProjectDetails.cshtml
@model MySolution.Model.Project
@{

}
<div class="content">  
<div>
    <p class="part">List of Tasks</p>
        <ul>
        @foreach(var task in @Model.Tasks)
        {
            <li><im>@task.Title</im>, assigned to <im>@task.Contributor</im> , and now it is on <im>@task.Status</im> status.</li>
        }
        </ul>
</div>

&emsp; 
<div>
    <p class="part">List of Users</p>
        <ul>
        @foreach(var user in @Model.Contributors)
        {
            <li><a class="link" href='@Url.Action("UserDetails", "Users", new {userName = @user})'>@user</a></li>
        }
    </ul>
</div>
</div>

Project Management Application - MVC/Views/Search/Index.cshtml
@model IEnumerable<MySolution.Model.MyTask>
<form asp-action="Index" asp-controller="Search" method="post">
    <h4>Search on tasks</h4>
    <table>
        <tr>
            <td>Project Name: </td>
            <td>@Html.TextBox("ProjectName")</td>
        </tr>
        <tr>
            <td>Task Name: </td>
            <td>@Html.TextBox("TaskName")</td>
        </tr>
        <tr>
            <td>Task Status: </td>
            <td>@Html.TextBox("TaskStatus")</td>
        </tr>
         <tr>
            <td>Assigned Contributor: </td>
            <td>@Html.TextBox("AssignedContributor")</td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="Search" /></td>
        </tr>
    </table>
    <hr/>
    <h4>Tasks: </h4>
    <table class="table">
    @{
        if(@Model.Count()==0)
        {
            <tr>
                <td></td>
            </tr>
        }
        else
        {
            foreach(var task in Model)
            {
                <tr>
                    <td>@task</td>
                </tr>
            }
        }
    }
    </table>
</form>

Project Management Application - MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Management_Application_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_Management_Application_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand logo"  asp-area="" asp-controller="Home" asp-action="Index">ProLine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="options navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li style="font-size :20px; padding-top : 10px" class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item" style="font-size :20px; padding-top : 10px">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div style="min-height:100vh" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Project_Management_Application_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project Management Application - MVC/Views/Users/UserDetails.cshtml
@model IEnumerable<MySolution.Model.Project>

<h4 class="title">@ViewBag.UserName</h4>
<div class="content">
    @{
        var item = @ViewBag.UserName;
        foreach(var project in Model)
        {
            <p>Works on <b>@project.ProjectName</b></p>
            <ul>
                @{
                    foreach (var task in project.Tasks)
                    {
                        if(task.Contributor.Equals(@ViewBag.UserName))
                        {
                            <li>@task </li>
                        }
                    }
                }
            </ul>
        }
    }
</div>